[package]
name = "srtemplate"
version = "0.1.0"
edition = "2021"

[features]
default = ["text", "os", "number"]
text = []
os = []
number = []

[dependencies]
nom = "7.1.3"
anyhow = "1.0.75"
thiserror = "1.0.49"
concat-idents = "1.1.5"
