[package]
name = "srtemplate_macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = { version = "2.0.37", features = ["fold", "full"] }

[dev-dependencies]
srtemplate = { path = "../srtemplate" }
